-- Vendored verbatim from LazyVim/starter -- intentionally empty
-- extension point, not a gap in this work (see design doc).
-- Keymaps are automatically loaded on the VeryLazy event
-- Default keymaps that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/keymaps.lua
-- Add any additional keymaps here
