-- Vendored verbatim from LazyVim/starter -- intentionally empty
-- extension point, not a gap in this work (see design doc).
-- Options are automatically loaded before lazy.nvim startup
-- Default options that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/options.lua
-- Add any additional options here
